# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# language: objective-c
# # cache: cocoapods
# # podfile: Example/Podfile
# # before_install:
# # - gem install cocoapods # Since Travis is not always on latest version
# # - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -scheme KRProgressHUD -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint

language: objective-c
osx_image: xcode7.3.1
xcode_project: KRProgressHUD.xcodeproj
xcode_scheme: KRProgressHUD
xcode_sdk: iphonesimulator
